export const styles = {
  container: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#f8f8f8",
  },
  sidebar: {
    width: "20%",
    backgroundColor: "#333",
    color: "#fff",
    padding: "20px",
    height: "100vh",
    position: "sticky",
    top: 0,
    boxShadow: "2px 0 5px rgba(0, 0, 0, 0.1)",
  },
  sidebarTitle: {
    fontSize: "24px",
    fontWeight: "bold",
    marginBottom: "20px",
  },
  nav: {
    display: "flex",
    flexDirection: "column",
  },
  navButton: {
    backgroundColor: "#0070f3",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "10px",
    margin: "10px 0",
    cursor: "pointer",
    width: "100%",
    textAlign: "center",
  },
  navButtonLogout: {
    backgroundColor: "orangered",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "10px",
    margin: "10px 0",
    cursor: "pointer",
    width: "100%",
    textAlign: "center",
  },
  navButtonDisabled: {
    backgroundColor: "grey",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "10px",
    margin: "10px 0",
    width: "100%",
    textAlign: "center",
  },
  mainContent: {
    width: "80%",
    padding: "10px",
    overflowY: "auto",
  },
  card: {
    padding: "20px",
    borderRadius: "8px",
    backgroundColor: "#fff",
    boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.1)",
    height: "auto",
    color: "black"
  },
  chartPlaceholder: {
    backgroundColor: "#eee",
    padding: "10px",
    marginBottom: "20px",
    textAlign: "center",
    borderRadius: "8px",
  },
  feed: {
    backgroundColor: "#f0f0f0",
    padding: "10px",
    borderRadius: "8px",
  },
  cardContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: "20px",
    marginTop: "20px",
  },
  cardAlt: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "dodgerblue",
    padding: "20px",
    borderRadius: "8px",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    textAlign: "center",
    minHeight: "120px",
  },
  cardContents: {
    fontSize: "24px", 
    color: "white", 
    fontWeight: 800, 
    marginTop: "5px"
  },
};
