name: Deploy to Azure App Service (Backend)

on:
  pull_request:
    branches:
      - prod
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Change to backend directory
        working-directory: backend
        run: echo "Changed to backend directory"

      - name: Install dependencies
        working-directory: .
        run: |
          python3 -m venv antenv
          . antenv/bin/activate
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          pip install -r requirements.txt
          pip install "pymongo[srv]"
          pip install --upgrade pydantic
          pip install gunicorn

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ./backend

      - name: Set environment variables and startup command
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az webapp config appsettings set --resource-group prima-pizza-rg-west --name ${{ secrets.AZURE_WEBAPP_NAME }} --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
          az webapp config set --resource-group prima-pizza-rg --name ${{ secrets.AZURE_WEBAPP_NAME }} --startup-file "gunicorn -w 4 -b 0.0.0.0:8000 startup:app"
