name: Deploy to Azure App Service (Backend)

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Change to backend directory
        working-directory: ./backend
        run: echo "Changed to backend directory"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python3 -m venv antenv
          . antenv/bin/activate
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          pip install -r requirements.txt
          pip install "pymongo[srv]"
          pip install --upgrade pydantic
          pip install gunicorn

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: .

      - name: Set environment variables and startup command
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az webapp config appsettings set --resource-group prima-pizza-rg --name ${{ secrets.AZURE_WEBAPP_NAME }} --settings FLASK_APP=services/prima_pizza/app.py FLASK_ENV=production ENV=PROD JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} DATABASE_URL=${{ secrets.DATABASE_URL }}
          az webapp config set --resource-group prima-pizza-rg --name ${{ secrets.AZURE_WEBAPP_NAME }} --startup-file "cd /home/site/wwwroot/backend && . antenv/bin/activate && export PATH=$HOME/.local/bin:$HOME/antenv/bin:$PATH && exec gunicorn -w 4 -b 0.0.0.0:8000 startup:app"
