# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - prima-pizza-backend-west

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set environment variables for deployment
        run: |
          echo "ENV=PROD" > .env
          echo "PORT=8000" >> .env
          echo "FLASK_APP=app.py" >> .env
          echo "FLASK_ENV=production" >> .env

      - name: Zip artifact for deployment
        run: |
          cd ..
          zip -r release.zip ./backend

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          ls -la
          echo "Current directory contents:"
          pwd
          find backend -type f -name "*.py" | sort

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_27DF159E9A0844BB97B6CAC22D245012 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F923D691F2CF4C72B36E641F24BA0BCA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C96D4689E28244EA98C68688C48ECF1B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'prima-pizza-backend-west'
          slot-name: 'Production'
          package: backend
          startup-command: 'gunicorn --bind=0.0.0.0:8000 --workers=4 --timeout=600 --preload app:app'

      - name: Configure Web App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set \
              --resource-group prima-pizza-rg-west \
              --name prima-pizza-backend-west \
              --linux-fx-version "PYTHON|3.10" \
              --startup-file ""

      - name: Configure App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --resource-group prima-pizza-rg-west \
              --name prima-pizza-backend-west \
              --settings \
                SCM_DO_BUILD_DURING_DEPLOYMENT=true \
                ENABLE_ORYX_BUILD=true \
                PYTHONPATH="/home/site/wwwroot" \
                ENV="PROD" \
                PORT="8000" \
                FLASK_APP="app.py" \
                WEBSITE_WEBDEPLOY_USE_SCM=false \
                FLASK_ENV="production"
