name: Azure Web App - prima-pizza-backend-west

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check Python version
        run: python --version

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: |
          source antenv/bin/activate
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r backend/requirements.txt
          python -m pip install flask-cors==3.0.10 pymongo[srv]

      - name: List contents of antenv/bin
        run: |
          ls -la antenv/bin

      - name: List installed packages
        run: |
          source antenv/bin/activate
          pip freeze

      - name: Prepare deployment package
        run: |
          cd backend
          cp -r ../antenv ./ 
          zip -r ../release.zip . .env antenv

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d .
          ls -la

      - name: Set execute permissions on Python executable
        run: chmod +x antenv/bin/python3

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Configure Azure Web App
        run: |
          # Set all environment variables and app settings in one command
          az webapp config appsettings set --resource-group prima-pizza-rg-west --name prima-pizza-backend-west --settings \
            ENV=PROD \
            DATABASE_URL="${{ secrets.MONGODB_URI }}" \
            TEST_DATABASE_URL="${{ secrets.TEST_MONGODB_URI }}" \
            PORT=8000 \
            WEBSITES_PORT=8000 \
            FLASK_APP="services.prima_pizza.app" \
            FLASK_ENV=production \
            JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
            CLIENT_APP="https://white-forest-0d702341e.6.azurestaticapps.net" \
            ALLOWED_ORIGINS="https://white-forest-0d702341e.6.azurestaticapps.net" \
            CORS_ENABLED=true \
            CORS_ALLOW_CREDENTIALS=false \
            WEBSITE_CORS_ALLOWED_ORIGINS="https://white-forest-0d702341e.6.azurestaticapps.net" \
            WEBSITE_CORS_SUPPORT_CREDENTIALS=false \
            WEBSITE_AUTH_ENABLED=False

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'prima-pizza-backend-west'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Set startup command
        run: |
          az webapp config set --resource-group prima-pizza-rg-west --name prima-pizza-backend-west --startup-file '. antenv/bin/activate && python3 -m services.prima_pizza.app'