name: Azure Web App - prima-pizza-backend-west

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: |
          source antenv/bin/activate
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r backend/requirements.txt
          python -m pip install flask-cors==3.0.10 pymongo[srv]

      - name: Prepare deployment package
        run: |
          mkdir -p deploy_package
          cp -r backend/* deploy_package/
          cp -r antenv deploy_package/
          cd deploy_package
          zip -r ../clean_release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: clean_release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Retry DNS Resolution
        run: |
          for i in {1..5}; do
            if curl -s --head --request GET https://prima-pizza-backend-west.scm.azurewebsites.net | grep "200 OK" > /dev/null; then
              echo "DNS resolved successfully"
              break
            else
              echo "DNS resolution failed, retrying in 30 seconds..."
              sleep 30
            fi
          done

      # - name: Clean up previous deployment
      #   run: |
      #     CREDS=$(az webapp deployment list-publishing-credentials --resource-group prima-pizza-rg-west --name prima-pizza-backend-west --query "{username:publishingUserName, password:publishingPassword}" -o json)
      #     USERNAME=$(echo $CREDS | jq -r '.username')
      #     PASSWORD=$(echo $CREDS | jq -r '.password')
      #     curl -u "$USERNAME:$PASSWORD" -X DELETE "https://prima-pizza-backend-west.scm.azurewebsites.net/api/vfs/site/wwwroot/*"

      - name: Restart Web App before deployment
        run: |
          az webapp restart --resource-group prima-pizza-rg-west --name prima-pizza-backend-west
          sleep 30

      - name: Unzip artifact for deployment
        run: |
          unzip -o clean_release.zip -d .

      - name: Configure Azure Web App
        run: |
          az webapp config appsettings set --resource-group prima-pizza-rg-west --name prima-pizza-backend-west --settings \
            ENV=PROD \
            DATABASE_URL="${{ secrets.MONGODB_URI }}" \
            TEST_DATABASE_URL="${{ secrets.TEST_MONGODB_URI }}" \
            PORT=8000 \
            WEBSITES_PORT=8000 \
            FLASK_APP="services.prima_pizza.app" \
            FLASK_ENV=production \
            JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
            CLIENT_APP="https://mango-meadow-0d2cf901e.6.azurestaticapps.net" \
            ALLOWED_ORIGINS="https://mango-meadow-0d2cf901e.6.azurestaticapps.net" \
            CORS_ENABLED=true \
            CORS_ALLOW_CREDENTIALS=false \
            WEBSITE_CORS_ALLOWED_ORIGINS="https://mango-meadow-0d2cf901e.6.azurestaticapps.net" \
            WEBSITE_CORS_SUPPORT_CREDENTIALS=false

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'prima-pizza-backend-west'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Set startup command
        run: |
          az webapp config set --resource-group prima-pizza-rg-west --name prima-pizza-backend-west --startup-file 'python3 -m services.prima_pizza.app'

      - name: Verify deployment
        run: |
          CREDS=$(az webapp deployment list-publishing-credentials --resource-group prima-pizza-rg-west --name prima-pizza-backend-west --query "{username:publishingUserName, password:publishingPassword}" -o json)
          USERNAME=$(echo $CREDS | jq -r '.username')
          PASSWORD=$(echo $CREDS | jq -r '.password')
          curl -u "$USERNAME:$PASSWORD" https://prima-pizza-backend-west.scm.azurewebsites.net/api/vfs/site/wwwroot/ | jq '.[].name'
