name: Build and deploy Python app to Azure Web App - prima-pizza-backend-west

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        working-directory: ./backend
        run: |
          python -m venv antenv
          . antenv/bin/activate

      - name: Install dependencies
        working-directory: ./backend
        run: |
          . antenv/bin/activate
          pip install -r requirements.txt
          export PORT=${PORT:-8000}

      - name: Debug artifact path
        working-directory: ./backend
        run: ls -la
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./backend
            ./backend/antenv

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }
    permissions:
      id-token: write
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./backend

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set environment variables
        run: |
          az webapp config appsettings set --resource-group prima-pizza-rg-west --name prima-pizza-backend-west --settings ENV=PROD MONGODB_URI=${{ secrets.MONGODB_URI }}

      - name: 'Deploy to Azure Web App'
        uses: Azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'prima-pizza-backend-west'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend
