name: Build and deploy Python app to Azure Web App - prima-pizza-backend-west

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: |
          source antenv/bin/activate
          python -m pip install -r backend/requirements.txt
          python -m pip install flask-cors==3.0.10 gunicorn==23.0.0 pymongo[srv]

      - name: Prepare deployment package
        run: |
          cd backend
          cp -r ../antenv ./
          zip -r ../release.zip . .env antenv web.config

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d .
          ls -la

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Configure Azure Web App
        uses: azure/appservice-settings@v1
        with:
          app-name: 'prima-pizza-backend-west'
          slot-name: 'Production'
          app-settings-json: |
            {
              "WEBSITES_PORT": "8000",
              "FLASK_ENV": "production",
              "SCM_DO_BUILD_DURING_DEPLOYMENT": "true",
              "CORS_ENABLED": "true",
              "CORS_ORIGINS": "https://prima-pizza.vercel.app,https://localhost:3000",
              "CORS_ALLOW_CREDENTIALS": "true",
              "CORS_METHODS": "GET,POST,PUT,DELETE,OPTIONS",
              "CORS_HEADERS": "Content-Type,Authorization,Accept,Origin,X-Requested-With",
              "WEBSITE_HTTPLOGGING_RETENTION_DAYS": "7",
              "FLASK_APP": "startup:app",
              "ENV": "PROD"
            }

      - name: Configure Web App General Settings
        run: |
          az webapp config set \
            --resource-group prima-pizza-rg-west \
            --name prima-pizza-backend-west \
            --ftps-state Disabled \
            --http20-enabled true \
            --min-tls-version 1.2 \
            --web-sockets-enabled false

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'prima-pizza-backend-west'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Set startup command
        run: |
          az webapp config set --resource-group prima-pizza-rg-west --name prima-pizza-backend-west --startup-file 'gunicorn --bind=0.0.0.0:8000 --timeout 220 startup:app'
